### ISSUE TITLE
Build Login Frontend

### ISSUE THREAD

**Issue by shreythecray** [Bearers-of-Worldly-Spirits/main_app#1]

**Comment by ghost** [comment]
<img width="518" alt="Screen Shot 2021-02-02 at 8 07 26 PM" src="https://user-images.githubusercontent.com/25429471/106696788-4740ed00-6592-11eb-989a-0755ec850871.png">

**Comment by ghost** [comment]
Still need to build a few more screens for the login but it is well underway.
